// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Robot is an autogenerated mock type for the Robot type
type Robot struct {
	mock.Mock
}

// SayHi provides a mock function with given fields:
func (_m *Robot) SayHi() {
	_m.Called()
}
